name: medireminder
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_ml_kit: ^0.16.3
  image_picker: ^1.0.7
  persistent_bottom_nav_bar: ^5.0.2
  table_calendar: ^3.1.1
  get_it: ^7.6.7

  cupertino_icons: ^1.0.6
  googleapis: ^13.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  http: ^1.1.0
  google_sign_in: ^6.2.1
  string_similarity: ^2.0.0
  sqflite: ^2.3.2
  path: ^1.9.0
  awesome_notifications: ^0.9.3+1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  file_picker: ^8.0.0+1
  googleapis_auth: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  image: ^4.1.7

  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
